// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD9QUC66hFzopeX2PXqRAsulQ_ib19DUjY',
    appId: '1:492173984525:web:ea7b0b27b5444955e62644',
    messagingSenderId: '492173984525',
    projectId: 'studee-educational',
    authDomain: 'studee-educational.firebaseapp.com',
    storageBucket: 'studee-educational.appspot.com',
    measurementId: 'G-5XQXFKTK7N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC2qnMOccAeTXpYAQ24-ruUmO59Ht4DmSw',
    appId: '1:492173984525:android:3d7a2986ee442df7e62644',
    messagingSenderId: '492173984525',
    projectId: 'studee-educational',
    storageBucket: 'studee-educational.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDa61fenbQ6P-netnehtGhSOi-008JEGy4',
    appId: '1:492173984525:ios:3ce1ac8623bc7b40e62644',
    messagingSenderId: '492173984525',
    projectId: 'studee-educational',
    storageBucket: 'studee-educational.appspot.com',
    iosBundleId: 'com.example.studeeEducational',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDa61fenbQ6P-netnehtGhSOi-008JEGy4',
    appId: '1:492173984525:ios:3ce1ac8623bc7b40e62644',
    messagingSenderId: '492173984525',
    projectId: 'studee-educational',
    storageBucket: 'studee-educational.appspot.com',
    iosBundleId: 'com.example.studeeEducational',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD9QUC66hFzopeX2PXqRAsulQ_ib19DUjY',
    appId: '1:492173984525:web:14057cfc60449b1de62644',
    messagingSenderId: '492173984525',
    projectId: 'studee-educational',
    authDomain: 'studee-educational.firebaseapp.com',
    storageBucket: 'studee-educational.appspot.com',
    measurementId: 'G-Y68968KC80',
  );
}
